// Generated by CoffeeScript 1.4.0
(function() {
  var JSV, d3, fs;

  d3 = require("d3");

  JSV = (require("JSV")).JSV;

  if (!(d3 != null) || !(JSV != null)) {
    console.log("cannot find d3 or JSV, use command: coffee -r d3 -r JSV _convert.coffee");
    return;
  }

  fs = require("fs");

  fs.readdir("./", function(error, files) {
    var filename, jsonData, jsonFilename, report, schemaData, schemaFilename, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      filename = files[_i];
      if (!(filename.match(".csv"))) {
        continue;
      }
      console.log("converting csv : " + filename);
      jsonData = d3.csv.parse(String(fs.readFileSync(filename)));
      schemaFilename = filename.replace(".csv", ".schema.json");
      if (fs.existsSync(schemaFilename)) {
        schemaData = JSON.parse(String(fs.readFileSync(schemaFilename)));
        report = JSV.createEnvironment().validate(jsonData, schemaData);
        if (report.errors.length !== 0) {
          console.log(report.errors);
          console.log("validate fail, schema : " + schemaFilename);
        } else {
          console.log("validate success by : " + schemaFilename);
        }
      }
      jsonFilename = filename.replace(".csv", ".json");
      fs.writeFileSync(jsonFilename, JSON.stringify(jsonData));
      _results.push(console.log("write csv: " + filename + " , to json: " + jsonFilename));
    }
    return _results;
  });

}).call(this);
